server:
  port: 8080

# config db
spring:
  datasource:
    url: jdbc:postgresql://${SERVER_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: ${FLYWAY_ENABLE}
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  jackson:
    default-property-inclusion: always

# logger
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE